//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rushtell_Bunk
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EDMdbRushBank : DbContext
    {
        public EDMdbRushBank()
            : base("name=EDMdbRushBank")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Organizations> Organizations { get; set; }
        public virtual DbSet<VIPworkers> VIPworkers { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
