//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rushtell_Bunk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int Id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public int age { get; set; }
        public int salary { get; set; }
        public double deposit { get; set; }
        public int methodPayments { get; set; }
        public int mounthCreateStandartPaymentMeth { get; set; }
        public string depositType { get; set; }
        public string type { get; set; }
    }
}
